export const OPENAI_KEY = process.env.REACT_APP_OPENAI_KEY;

export const API_OPTIONS = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization: "Bearer " + process.env.REACT_APP_TMDB_KEY,
  },
};

export const IMG_CDN_URL = "https://image.tmdb.org/t/p/original/";

export const BACKGROUND_IMG =
  "https://assets.nflxext.com/ffe/siteui/vlv3/93da5c27-be66-427c-8b72-5cb39d275279/94eb5ad7-10d8-4cca-bf45-ac52e0a052c0/IN-en-20240226-popsignuptwoweeks-perspective_alpha_website_medium.jpg";

export const SUPPORTED_LANGUAGES = [
  { identifier: "en", name: "English" },
  { identifier: "hindi", name: "Hindi" },
  { identifier: "spanish", name: "Spanish" },
];

// filter trailer from this
export const FIRST_MOVIE_VIDEOS = [
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Clip",
    key: "UJa1zUYegqo",
    site: "YouTube",
    size: 1080,
    type: "Clip",
    official: true,
    published_at: "2024-02-16T16:31:54.000Z",
    id: "65d40e001d356301631e68cb",
  },
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Official Trailer",
    key: "e1k1PC0TtmE",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: true,
    published_at: "2023-11-30T13:02:56.000Z",
    id: "65880cfc5aba326759b95156",
  },
];

export const DUMMY_NOW_PLAYING_MOVIES = [
  {
    adult: false,
    backdrop_path: "/a3F9cXjRH488qcOqFmFZwqawBMU.jpg",
    genre_ids: [16, 28, 878],
    id: 1376434,
    original_language: "en",
    original_title: "Predator: Killer of Killers",
    overview:
      "This original animated anthology follows three of the fiercest warriors in human history: a Viking raider guiding her young son on a bloody quest for revenge, a ninja in feudal Japan who turns against his Samurai brother in a brutal battle for succession, and a WWII pilot who takes to the sky to investigate an otherworldly threat to the Allied cause.",
    popularity: 784.5698,
    poster_path: "/lbimIPTVsSlnmqSW5ngEsUxtHLM.jpg",
    release_date: "2025-06-05",
    title: "Predator: Killer of Killers",
    video: false,
    vote_average: 8.0,
    vote_count: 401,
  },
  {
    adult: false,
    backdrop_path: "/yBDvgpyynDsbMyK21FoQu1c2wYR.jpg",
    genre_ids: [9648, 80, 53],
    id: 870028,
    original_language: "en",
    original_title: "The Accountant²",
    overview:
      "When an old acquaintance is murdered, Wolff is compelled to solve the case. Realizing more extreme measures are necessary, Wolff recruits his estranged and highly lethal brother, Brax, to help. In partnership with Marybeth Medina, they uncover a deadly conspiracy, becoming targets of a ruthless network of killers who will stop at nothing to keep their secrets buried.",
    popularity: 585.1611,
    poster_path: "/kMDUS7VmFhb2coRfVBoGLR8ADBt.jpg",
    release_date: "2025-04-23",
    title: "The Accountant²",
    video: false,
    vote_average: 7.2,
    vote_count: 667,
  },
  {
    adult: false,
    backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
    genre_ids: [10751, 878, 35, 12],
    id: 552524,
    original_language: "en",
    original_title: "Lilo & Stitch",
    overview:
      "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
    popularity: 457.1902,
    poster_path: "/7c5VBuCbjZOk7lSfj9sMpmDIaKX.jpg",
    release_date: "2025-05-17",
    title: "Lilo & Stitch",
    video: false,
    vote_average: 7.102,
    vote_count: 604,
  },
  {
    adult: false,
    backdrop_path: "/ycAJkh9wATOO5bsyNCjBP5dO5Jb.jpg",
    genre_ids: [53, 18, 80],
    id: 1426776,
    original_language: "en",
    original_title: "STRAW",
    overview:
      "What will be her last straw? A devastatingly bad day pushes a hardworking single mother to the breaking point — and into a shocking act of desperation.",
    popularity: 485.8583,
    poster_path: "/t3cmnXYtxJb9vVL1ThvT2CWSe1n.jpg",
    release_date: "2025-06-05",
    title: "STRAW",
    video: false,
    vote_average: 8.308,
    vote_count: 274,
  },
  {
    adult: false,
    backdrop_path: "/rU9kRB3rBU5O7AMReZCiuIy7zmE.jpg",
    genre_ids: [28, 18, 12],
    id: 1450599,
    original_language: "fr",
    original_title: "K.O.",
    overview:
      "A former fighter must find the missing son of an opponent he accidentally killed years ago, taking on a brutally violent crime gang in Marseille.",
    popularity: 390.6131,
    poster_path: "/qcM2sUiAeP4zXwx4ADSvgc9S58k.jpg",
    release_date: "2025-06-05",
    title: "K.O.",
    video: false,
    vote_average: 6.873,
    vote_count: 83,
  },
  {
    adult: false,
    backdrop_path: "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
    genre_ids: [27, 53],
    id: 1233413,
    original_language: "en",
    original_title: "Sinners",
    overview:
      "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
    popularity: 333.1718,
    poster_path: "/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
    release_date: "2025-04-16",
    title: "Sinners",
    video: false,
    vote_average: 7.553,
    vote_count: 1385,
  },
  {
    adult: false,
    backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
    genre_ids: [27, 9648],
    id: 574475,
    original_language: "en",
    original_title: "Final Destination Bloodlines",
    overview:
      "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
    popularity: 222.4848,
    poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
    release_date: "2025-05-14",
    title: "Final Destination Bloodlines",
    video: false,
    vote_average: 7.0,
    vote_count: 634,
  },
  {
    adult: false,
    backdrop_path: "/v67tbCB03CMcJRWit8CS7JdJp6.jpg",
    genre_ids: [28, 53, 18],
    id: 757725,
    original_language: "en",
    original_title: "Shadow Force",
    overview:
      "Kyrah and Isaac were once the leaders of a multinational special forces group called Shadow Force. They broke the rules by falling in love, and in order to protect their son, they go underground. With a large bounty on their heads, and the vengeful Shadow Force hot on their trail, one family's fight becomes all-out war.",
    popularity: 197.0645,
    poster_path: "/7IEW24vBiZerZrDlgLVSUU3oT1C.jpg",
    release_date: "2025-05-01",
    title: "Shadow Force",
    video: false,
    vote_average: 6.341,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/5IbxcBXZ5EhVAttfNDMPncikudr.jpg",
    genre_ids: [28, 53, 80],
    id: 541671,
    original_language: "en",
    original_title: "Ballerina",
    overview:
      "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    popularity: 205.8472,
    poster_path: "/mKp4euM5Cv3m2U1Vmby3OGwcD5y.jpg",
    release_date: "2025-06-04",
    title: "Ballerina",
    video: false,
    vote_average: 7.119,
    vote_count: 232,
  },
  {
    adult: false,
    backdrop_path: "/8FLzVS8AlhyAMSgzcsZukCKG15c.jpg",
    genre_ids: [27, 9648, 53],
    id: 713364,
    original_language: "en",
    original_title: "Clown in a Cornfield",
    overview:
      "Quinn and her father have just moved to the quiet town of Kettle Springs hoping for a fresh start. Instead, she discovers a fractured community that has fallen on hard times after the treasured Baypen Corn Syrup Factory burned down. As the locals bicker amongst themselves and tensions boil over, a sinister, grinning figure emerges from the cornfields to cleanse the town of its burdens, one bloody victim at a time.",
    popularity: 183.8682,
    poster_path: "/6ep6gw90TJ8bYvJC6hEDo8SxjoJ.jpg",
    release_date: "2025-05-08",
    title: "Clown in a Cornfield",
    video: false,
    vote_average: 6.3,
    vote_count: 64,
  },
  {
    adult: false,
    backdrop_path: "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
    genre_ids: [28, 10751, 14],
    id: 1087192,
    original_language: "en",
    original_title: "How to Train Your Dragon",
    overview:
      "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    popularity: 205.1135,
    poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
    release_date: "2025-06-06",
    title: "How to Train Your Dragon",
    video: false,
    vote_average: 7.75,
    vote_count: 104,
  },
  {
    adult: false,
    backdrop_path: "/eQV9rSQ6S1ja4lGTwHTnQuVhoG.jpg",
    genre_ids: [27, 35, 14, 18],
    id: 1284120,
    original_language: "no",
    original_title: "Den stygge stesøsteren",
    overview:
      "In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.",
    popularity: 162.5131,
    poster_path: "/crX9rSg9EohybhkEe8iTQUCe55y.jpg",
    release_date: "2025-03-07",
    title: "The Ugly Stepsister",
    video: false,
    vote_average: 7.052,
    vote_count: 154,
  },
  {
    adult: false,
    backdrop_path: "/aEG09hZZEDZ23Y9WYI701W6Gwnb.jpg",
    genre_ids: [28, 12, 53],
    id: 575265,
    original_language: "en",
    original_title: "Mission: Impossible - The Final Reckoning",
    overview:
      "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
    popularity: 156.2172,
    poster_path: "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
    release_date: "2025-05-17",
    title: "Mission: Impossible - The Final Reckoning",
    video: false,
    vote_average: 7.142,
    vote_count: 746,
  },
  {
    adult: false,
    backdrop_path: "/cJvUJEEQ86LSjl4gFLkYpdCJC96.jpg",
    genre_ids: [10752, 28],
    id: 1241436,
    original_language: "en",
    original_title: "Warfare",
    overview:
      "A platoon of Navy SEALs embarks on a dangerous mission in Ramadi, Iraq, with the chaos and brotherhood of war retold through their memories of the event.",
    popularity: 107.7305,
    poster_path: "/srj9rYrjefyWqkLc6l2xjTGeBGO.jpg",
    release_date: "2025-04-09",
    title: "Warfare",
    video: false,
    vote_average: 7.291,
    vote_count: 522,
  },
  {
    adult: false,
    backdrop_path: "/I1relwnq4IZ0IOcLxPyyjaiOoN.jpg",
    genre_ids: [27, 28, 12, 53],
    id: 1232933,
    original_language: "en",
    original_title: "Fear Below",
    overview:
      "A rag-tag team of divers attempting to salvage a sunken car from a river are thwarted by a highly aggressive bull shark.",
    popularity: 103.773,
    poster_path: "/obK2G8huZWeAQEgOz1I47AkzHYh.jpg",
    release_date: "2025-05-02",
    title: "Fear Below",
    video: false,
    vote_average: 6.728,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/tyfO9jHgkhypUFizRVYD0bytPjP.jpg",
    genre_ids: [10751, 14],
    id: 447273,
    original_language: "en",
    original_title: "Snow White",
    overview:
      "Following the benevolent King's disappearance, the Evil Queen dominated the once fair land with a cruel streak. Princess Snow White flees the castle when the Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young bandit named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom.",
    popularity: 108.4386,
    poster_path: "/oLxWocqheC8XbXbxqJ3x422j9PW.jpg",
    release_date: "2025-03-12",
    title: "Snow White",
    video: false,
    vote_average: 4.277,
    vote_count: 1057,
  },
  {
    adult: false,
    backdrop_path: "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
    genre_ids: [28, 14, 12],
    id: 324544,
    original_language: "en",
    original_title: "In the Lost Lands",
    overview:
      "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.",
    popularity: 88.5391,
    poster_path: "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
    release_date: "2025-02-27",
    title: "In the Lost Lands",
    video: false,
    vote_average: 6.46,
    vote_count: 466,
  },
  {
    adult: false,
    backdrop_path: "/icFWIk1KfkWLZnugZAJEDauNZ94.jpg",
    genre_ids: [27, 9648],
    id: 1232546,
    original_language: "en",
    original_title: "Until Dawn",
    overview:
      "One year after her sister Melanie mysteriously disappeared, Clover and her friends head into the remote valley where she vanished in search of answers. Exploring an abandoned visitor center, they find themselves stalked by a masked killer and horrifically murdered one by one...only to wake up and find themselves back at the beginning of the same evening.",
    popularity: 89.5947,
    poster_path: "/juA4IWO52Fecx8lhAsxmDgy3M3.jpg",
    release_date: "2025-04-23",
    title: "Until Dawn",
    video: false,
    vote_average: 6.567,
    vote_count: 645,
  },
  {
    adult: false,
    backdrop_path: "/lAnkMSDISzMYLWICS7m16rSTUHD.jpg",
    genre_ids: [28, 12, 18],
    id: 1011477,
    original_language: "en",
    original_title: "Karate Kid: Legends",
    overview:
      "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    popularity: 69.203,
    poster_path: "/c90Lt7OQGsOmhv6x4JoFdoHzw5l.jpg",
    release_date: "2025-05-08",
    title: "Karate Kid: Legends",
    video: false,
    vote_average: 6.9,
    vote_count: 125,
  },
  {
    adult: false,
    backdrop_path: "/jRvhP4AfFnJ03lCQhp1fie7XPSd.jpg",
    genre_ids: [28, 53],
    id: 977294,
    original_language: "en",
    original_title: "Tin Soldier",
    overview:
      "An ex-special forces operative seeks revenge against a cult leader who has corrupted his former comrades, the Shinjas. This leader, known as The Bokushi, promises veterans a purpose and protection, but is revealed to be a destructive influence. The ex-soldier, Nash Cavanaugh, joins forces with military operative Emmanuel Ashburn to infiltrate the Bokushi's fortress and expose his reign of terror",
    popularity: 64.2751,
    poster_path: "/6HU667T8fxoIvgsgu2eyaznntsp.jpg",
    release_date: "2025-05-22",
    title: "Tin Soldier",
    video: false,
    vote_average: 4.944,
    vote_count: 54,
  },
];
export const DUMMY_POPULAR_MOVIES = [
  {
    adult: false,
    backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 1968.226,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.905,
    vote_count: 2157,
  },
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 1728.445,
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.858,
    vote_count: 81,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 1644.747,
    poster_path: "/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.113,
    vote_count: 529,
  },
  {
    adult: false,
    backdrop_path: "/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "pt",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1270.857,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.031,
    vote_count: 212,
  },
  {
    adult: false,
    backdrop_path: "/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg",
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: "en",
    original_title: "Megamind vs. the Doom Syndicate",
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 1036.743,
    poster_path: "/1N7terrMeZPwK5qq31MUD0HQ3IG.jpg",
    release_date: "2024-03-01",
    title: "Megamind vs. the Doom Syndicate",
    video: false,
    vote_average: 5.594,
    vote_count: 106,
  },
  {
    adult: false,
    backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
    genre_ids: [878, 28, 80],
    id: 932420,
    original_language: "en",
    original_title: "Code 8 Part II",
    overview:
      "In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
    popularity: 991.211,
    poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
    release_date: "2024-02-27",
    title: "Code 8 Part II",
    video: false,
    vote_average: 6.613,
    vote_count: 265,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 992.575,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.116,
    vote_count: 7117,
  },
  {
    adult: false,
    backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 1342.522,
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.422,
    vote_count: 1526,
  },
  {
    adult: false,
    backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 788.102,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.556,
    vote_count: 923,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 742.821,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.93,
    vote_count: 327,
  },
  {
    adult: false,
    backdrop_path: "/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
    genre_ids: [28, 80],
    id: 1046090,
    original_language: "zh",
    original_title: "周處除三害",
    overview:
      "The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
    popularity: 1050.574,
    poster_path: "/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
    release_date: "2023-10-06",
    title: "The Pig, the Snake and the Pigeon",
    video: false,
    vote_average: 7.592,
    vote_count: 76,
  },
  {
    adult: false,
    backdrop_path: "/midCh3iVxaG3dUOrP9TnUpNcGm.jpg",
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 737.001,
    poster_path: "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.5,
    vote_count: 1048,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 12, 28],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 1013.663,
    poster_path: "/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    release_date: "2024-03-08",
    title: "Damsel",
    video: false,
    vote_average: 7.315,
    vote_count: 580,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 676.392,
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 7.031,
    vote_count: 960,
  },
  {
    adult: false,
    backdrop_path: "/hIUs8RzKlrzgbWxn2EpWmiTFqCc.jpg",
    genre_ids: [878, 53],
    id: 870404,
    original_language: "en",
    original_title: "Meteor",
    overview:
      "After a meteor collides into Earth, a lonely rancher and a lost young girl are on the run from vicious mercenaries.",
    popularity: 591.223,
    poster_path: "/tVMddOS5bi3YPVPgTPlEw0TOWoF.jpg",
    release_date: "2021-09-01",
    title: "Meteor",
    video: false,
    vote_average: 5.444,
    vote_count: 80,
  },
  {
    adult: false,
    backdrop_path: "/6SLyu9ygASsrOqkCpjAwtyG9PWW.jpg",
    genre_ids: [10751, 878, 28, 35],
    id: 1094556,
    original_language: "en",
    original_title: "The Thundermans Return",
    overview:
      "Twins Phoebe and Max are enjoying their superhero lifestyle, but when one 'save' goes awry, the Thundermans are sent back to Hiddenville. While Hank and Barb enjoy their return, and Billy and Nora look forward to a normal high school life, Max and Phoebe are determined to regain their superhero status.",
    popularity: 574.846,
    poster_path: "/2J5eeroLDY0d45mVjpuGhcLZs3W.jpg",
    release_date: "2024-03-07",
    title: "The Thundermans Return",
    video: false,
    vote_average: 7.622,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/wqmemsQb8xcLVQkwt8WTYnMIYms.jpg",
    genre_ids: [28, 35],
    id: 1217409,
    original_language: "es",
    original_title: "Jaque Mate",
    overview:
      "Duque, an international secret agent who retired years ago after a traumatic event, is forced to return to action when a commando operative kidnaps his niece and forces him to steal a precious scientific formula as part of the ransom.",
    popularity: 609.513,
    poster_path: "/26VzK0GVAsZhVXIbv3qDKiwBYud.jpg",
    release_date: "2024-01-25",
    title: "Jaque Mate",
    video: false,
    vote_average: 4.7,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 734.998,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.786,
    vote_count: 10708,
  },
  {
    adult: false,
    backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 545.577,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.194,
    vote_count: 2500,
  },
  {
    adult: false,
    backdrop_path: "/td2NcEUn7MPWzpFFjvHLsVQ2pkZ.jpg",
    genre_ids: [28, 53],
    id: 984249,
    original_language: "en",
    original_title: "Ruthless",
    overview:
      "A high school coach, whose teenage daughter was murdered, takes matters into his own hands by going after the men who kidnap his students for their sex trafficking operation.",
    popularity: 472.816,
    poster_path: "/3hVt5fEuUxNZ5h6ynczcUbq6lpJ.jpg",
    release_date: "2023-12-14",
    title: "Ruthless",
    video: false,
    vote_average: 6.621,
    vote_count: 29,
  },
];

export const DUMMY_UPCOMING_MOVIES = [
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 1728.445,
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.813,
    vote_count: 83,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 992.575,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.116,
    vote_count: 7118,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 742.821,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.93,
    vote_count: 327,
  },
  {
    adult: false,
    backdrop_path: "/75nSb1fbWooipwcSU5bUttiOriI.jpg",
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 737.001,
    poster_path: "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.5,
    vote_count: 1049,
  },
  {
    adult: false,
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    genre_ids: [28, 53, 18],
    id: 866398,
    original_language: "en",
    original_title: "The Beekeeper",
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    popularity: 425.75,
    poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    release_date: "2024-01-08",
    title: "The Beekeeper",
    video: false,
    vote_average: 7.463,
    vote_count: 1683,
  },
  {
    adult: false,
    backdrop_path: "/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg",
    genre_ids: [16, 35, 18, 10751],
    id: 838240,
    original_language: "es",
    original_title: "Robot Dreams",
    overview:
      "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
    popularity: 323.303,
    poster_path: "/vSzOobYVu16MogSALNg1bjTaGc.jpg",
    release_date: "2023-10-20",
    title: "Robot Dreams",
    video: false,
    vote_average: 7.35,
    vote_count: 103,
  },
  {
    adult: false,
    backdrop_path: "/yKAg8z8T1iXeYA0Io3E4u9mchdt.jpg",
    genre_ids: [28, 878, 12],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 339.066,
    poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/fGe1ej335XbqN1j9teoDpofpbLX.jpg",
    genre_ids: [53, 9648, 80],
    id: 915935,
    original_language: "fr",
    original_title: "Anatomie d'une chute",
    overview:
      "A woman is suspected of her husband's murder, and their blind son faces a moral dilemma as the sole witness.",
    popularity: 327.745,
    poster_path: "/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
    release_date: "2023-08-23",
    title: "Anatomy of a Fall",
    video: false,
    vote_average: 7.676,
    vote_count: 1400,
  },
  {
    adult: false,
    backdrop_path: "/nvW0QfRJ7ga9TK8DKwBfAPA8ywP.jpg",
    genre_ids: [28, 18, 80],
    id: 944401,
    original_language: "en",
    original_title: "Dogman",
    overview:
      "A boy, bruised by life, finds his salvation through the love of his dogs.",
    popularity: 405.128,
    poster_path: "/rmRkZZ2aZq72dDTjbPnSLtPQcmJ.jpg",
    release_date: "2023-09-27",
    title: "Dogman",
    video: false,
    vote_average: 7.6,
    vote_count: 423,
  },
  {
    adult: false,
    backdrop_path: "/aINel9503ompOlGKn4sIVMg09Un.jpg",
    genre_ids: [9648, 27, 53],
    id: 838209,
    original_language: "ko",
    original_title: "파묘",
    overview:
      "After suffering from serial paranormal events, a wealthy family living in LA summons a young rising shaman duo Hwa-rim and Bong-gil to save the newborn of the family. Once they arrive, Hwa-rim senses a dark shadow of their ancestor has latched on the family, so-called a 'Grave's Calling'. In order to exhume the grave and relieve the ancestor, Hwa-rim seeks help from the top-notch geomancer Sang-duk and the mortician Young-geun. To their dismay, the four find the grave at a shady location in a remote village in Korea. Unaware of the consequences, the exhumation is carried out, yet this rather unleashes a malevolent force buried underneath.",
    popularity: 244.992,
    poster_path: "/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg",
    release_date: "2024-02-22",
    title: "Exhuma",
    video: false,
    vote_average: 8.625,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
    genre_ids: [36, 18, 10752],
    id: 467244,
    original_language: "en",
    original_title: "The Zone of Interest",
    overview:
      "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
    popularity: 290.073,
    poster_path: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    release_date: "2023-12-15",
    title: "The Zone of Interest",
    video: false,
    vote_average: 7.312,
    vote_count: 791,
  },
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
    popularity: 190.354,
    poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
    release_date: "2023-10-05",
    title: "Freelance",
    video: false,
    vote_average: 6.542,
    vote_count: 613,
  },
  {
    adult: false,
    backdrop_path: "/ae48U4187XzjJ7En7YTAIz2QKQC.jpg",
    genre_ids: [18],
    id: 976893,
    original_language: "ja",
    original_title: "PERFECT DAYS",
    overview:
      "Hirayama is content with his life as a toilet cleaner in Tokyo. Outside of his structured routine, he cherishes music on cassette tapes, books, and taking photos of trees. Through unexpected encounters, he reflects on finding beauty in the world.",
    popularity: 175.528,
    poster_path: "/hGNPzUOczCotGWygli2hJafV3P8.jpg",
    release_date: "2023-11-10",
    title: "Perfect Days",
    video: false,
    vote_average: 7.9,
    vote_count: 555,
  },
  {
    adult: false,
    backdrop_path: "/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg",
    genre_ids: [18],
    id: 1058694,
    original_language: "en",
    original_title: "Radical",
    overview:
      "In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.",
    popularity: 109.377,
    poster_path: "/eSatbygYZp8ooprBHZdb6GFZxGB.jpg",
    release_date: "2023-10-19",
    title: "Radical",
    video: false,
    vote_average: 8.385,
    vote_count: 317,
  },
  {
    adult: false,
    backdrop_path: "/47SVqaO02doJ06tOmrjiWDkwU3T.jpg",
    genre_ids: [28, 53],
    id: 927107,
    original_language: "en",
    original_title: "The Bricklayer",
    overview:
      "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
    popularity: 113.467,
    poster_path: "/36pYugctLa70NmwMEgXTR1G31Kq.jpg",
    release_date: "2023-12-14",
    title: "The Bricklayer",
    video: false,
    vote_average: 6,
    vote_count: 133,
  },
  {
    adult: false,
    backdrop_path: "/j11RoLbvHGmJsBHcKqvbZxc5drh.jpg",
    genre_ids: [18, 28, 53],
    id: 1053592,
    original_language: "es",
    original_title: "Todos los nombres de Dios",
    overview:
      "After being implicated in a terrorist attack, Santi, a taxi driver, is taken hostage by one of the perpetrators.",
    popularity: 102.575,
    poster_path: "/n15gfcgwV0LVPSobrayZcFHcwN6.jpg",
    release_date: "2023-09-15",
    title: "All the Names of God",
    video: false,
    vote_average: 6.5,
    vote_count: 61,
  },
  {
    adult: false,
    backdrop_path: "/lyHmhoRj3zXSdeCYbs2oOXLCF4K.jpg",
    genre_ids: [16, 12, 10751, 14],
    id: 459003,
    original_language: "uk",
    original_title: "Мавка: Лісова пісня",
    overview:
      "Forest soul Mavka faces an impossible choice between her heart and her duty as guardian to the Heart of the Forest, when she falls in love with the talented young human musician Lukas.",
    popularity: 98.877,
    poster_path: "/8v7g3nydS5Ga2wBgdCNC70Y9ykk.jpg",
    release_date: "2023-03-02",
    title: "Mavka: The Forest Song",
    video: false,
    vote_average: 7.294,
    vote_count: 624,
  },
  {
    adult: false,
    backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
    genre_ids: [16, 35, 14, 12, 10751],
    id: 508943,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    popularity: 105.838,
    poster_path: "/9x4i9uKGXt8IiiIF5Ey0DIoY738.jpg",
    release_date: "2021-06-17",
    title: "Luca",
    video: false,
    vote_average: 7.8,
    vote_count: 7960,
  },
  {
    adult: false,
    backdrop_path: "/7grv5ULlK9wMr2T1fkgr56HlbT.jpg",
    genre_ids: [18, 36, 10752],
    id: 760774,
    original_language: "en",
    original_title: "One Life",
    overview:
      "British stockbroker Nicholas Winton visits Czechoslovakia in the 1930s and forms plans to assist in the rescue of Jewish children before the onset of World War II, in an operation that came to be known as the Kindertransport.",
    popularity: 97.947,
    poster_path: "/yvnIWt2j8VnDgwKJE2VMiFMa2Qo.jpg",
    release_date: "2023-09-09",
    title: "One Life",
    video: false,
    vote_average: 7.668,
    vote_count: 191,
  },
  {
    adult: false,
    backdrop_path: "/4l65BWqJBl7hBwdIwp2nQdwsOuw.jpg",
    genre_ids: [18, 36],
    id: 850165,
    original_language: "en",
    original_title: "The Iron Claw",
    overview:
      "The true story of the inseparable Von Erich brothers, who made history in the intensely competitive world of professional wrestling in the early 1980s. Through tragedy and triumph, under the shadow of their domineering father and coach, the brothers seek larger-than-life immortality on the biggest stage in sports.",
    popularity: 89.652,
    poster_path: "/nfs7DCYhgrEIgxKYbITHTzKsggf.jpg",
    release_date: "2023-12-21",
    title: "The Iron Claw",
    video: false,
    vote_average: 7.535,
    vote_count: 343,
  },
];

export const DUMMY_TOP_RATED_MOVIES = [
  {
    adult: false,
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 136.526,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.704,
    vote_count: 25763,
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 160.8,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.695,
    vote_count: 19575,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 80.197,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.575,
    vote_count: 11826,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 82.462,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.565,
    vote_count: 15211,
  },
  {
    adult: false,
    backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 152.967,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.54,
    vote_count: 15641,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 72.544,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.539,
    vote_count: 8112,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 43.458,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.533,
    vote_count: 4355,
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 112.271,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 31599,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 131.193,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.51,
    vote_count: 17257,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 94.948,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.508,
    vote_count: 16594,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 122.671,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.496,
    vote_count: 10820,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 126.722,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.49,
    vote_count: 26776,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    popularity: 143.08,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.478,
    vote_count: 23142,
  },
  {
    adult: false,
    backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 137.44,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.477,
    vote_count: 26305,
  },
  {
    adult: false,
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 91.847,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.467,
    vote_count: 12223,
  },
  {
    adult: false,
    backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 106.388,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.466,
    vote_count: 8132,
  },
  {
    adult: false,
    backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.6,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.463,
    vote_count: 5148,
  },
  {
    adult: false,
    backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 52.335,
    poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.455,
    vote_count: 4143,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 50.356,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.5,
    vote_count: 12615,
  },
  {
    adult: false,
    backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 50.537,
    poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.5,
    vote_count: 3429,
  },
];
